import esbuild from "esbuild";
import { fileURLToPath } from "node:url";
import path from "node:path";
import process from "process";
import { builtinModules } from "node:module";

const rootDir = path.dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
To view the source, visit the GitHub repository of this plugin.
*/
`;

const prod = process.argv[2] === "production";

const buildOptions = {
	absWorkingDir: rootDir,
	banner: { js: banner },
	entryPoints: ["./src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "./main.js",
	minify: prod,
};

if (prod) {
	await esbuild.build(buildOptions);
} else {
	const context = await esbuild.context(buildOptions);
	await context.watch();
}
